deps: Update beam version to 2.24.0
googleapis/java-bigtable-hbase pull request #2857
Opened 2021-03-01 22:59 UTC by vermas2012

Porting https://github.com/googleapis/java-bigtable-hbase/pull/2775 to bigtable-1.x

2021-03-02 14:28 UTC, kolea2 requested changes
looks good, I think you also want to include the changes from https://github.com/googleapis/java-bigtable-hbase/issues/2788

2021-03-02 23:28 UTC, vermas2012 reviewed
Done.

2021-03-02 23:33 UTC, vermas2012 commented
> looks good, I think you also want to include the changes from #2789

Done.

2021-03-03 14:32 UTC, kolea2 approved these changes

2021-03-03 14:33 UTC, merged