chore: port cached channel pool to veneer backend
googleapis/java-bigtable-hbase pull request #2916
Opened 2021-04-02 15:44 UTC by igorbernstein2

This is an existing feature in bigtable-client-core that needed to be re-implemented for the transition to java-bigtable

2021-04-02 17:49 UTC, igorbernstein2 commented
Tests are fixed in #2917

2021-04-06 16:02 UTC, mutianf requested changes
Looks good, just noticed a typo in the class name :), and should the key use credentials instead of credentialsProvider?

2021-04-06 19:15 UTC, igorbernstein2 commented on bigtable-client-core-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/wrappers/veneer/SharedDataClientWrapperFactory.java
> +    private final CredentialsProvider credentialsProvider;
It has to be credentialsProvider. This class is used to check if we have a ClientContext for the given StubSettings. StubSettings contain providers, which will in most instances return a new instance of Credentials when getCredentials() is called. So the intention here is to reuse the same ClientContext when the StubSettings are using the same provider

2021-04-06 19:15 UTC, igorbernstein2 commented on bigtable-client-core-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/wrappers/veneer/SharedDataClentWrapper.java
> +class SharedDataClentWrapper implements DataClientWrapper {
😳

2021-04-06 19:20 UTC, mutianf approved these changes

2021-04-06 19:48 UTC, merged