feat: add client-core metrics to veneer
googleapis/java-bigtable-hbase pull request #2962
Opened 2021-05-07 14:04 UTC by mutianf

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/java-bigtable-hbase/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> ☕️

2021-05-07 18:59 UTC, mutianf commented on bigtable-client-core-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/wrappers/veneer/BigtableHBaseVeneerSettings.java
> +      channelProvider.setInterceptorProvider(new MetricsChannelInterceptorInterceptorProvider());
Note: Not sure about this part.. this won't include the interceptors that's already set in the setting, but looks like there isn't a way in InstantiatingGrpcChannelProvider to get interceptor provider from the builder https://github.com/googleapis/gax-java/blob/master/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java#L468-L471?

2021-05-11 15:16 UTC, mutianf commented on bigtable-client-core-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/wrappers/veneer/metrics/MetricsApiTracerAdapter.java
> +  private final Timer firstResponseLatencyTimer =
I think this metric won't show up in metric registery https://github.com/googleapis/java-bigtable-hbase/blob/master/bigtable-client-core-parent/bigtable-client-core/src/main/java/com/google/cloud/bigtable/grpc/scanner/ResponseQueueReader.java#L87-L106 (line 94 is where it's recorded)

2021-05-19 18:37 UTC, igorbernstein2 requested changes
looks good, but needs to fix channel dec when channelpooling is enabled

2021-05-19 18:37 UTC, igorbernstein2 commented on bigtable-client-core-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/wrappers/veneer/BigtableVeneerApi.java
> +    }
Doesnt this need to account for channel pooling as well? ie defer decrementing to the factory?

2021-05-19 18:44 UTC, igorbernstein2 commented on bigtable-client-core-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/wrappers/veneer/BigtableVeneerApi.java
> +    }
actually nevermind, channelPoolSize will be 0

2021-05-19 18:44 UTC, igorbernstein2 approved these changes
lgtm

2021-05-19 19:21 UTC, igorbernstein2 commented
closing in favor of #2978 (which fixes a minor dep issue)

2021-05-19 19:21 UTC, closed without merging