feat: Adding a detailed readme for HBase replication support.
googleapis/java-bigtable-hbase pull request #3527
Opened 2022-02-28 20:19 UTC by vermas2012

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/java-bigtable-hbase/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> ☕️

2022-02-28 20:21 UTC, vermas2012 commented
@jhambleton PTAL. I had to re-create another PR due to branch issues, I have addressed all the comments except one. https://github.com/googleapis/java-bigtable-hbase/pull/3525#discussion_r815237863

2022-02-28 21:20 UTC, vermas2012 commented
Updated the PR with some details on authentication. 

@jhambleton should we create a top level section on authentication along with configuration?

2022-02-28 22:38 UTC, jhambleton requested changes
thank you for incorporating other changes from pr#3525 here! all looks good with minor nit around timestamp incompatibility.

2022-02-28 22:38 UTC, jhambleton commented on hbase-migration-tools/bigtable-hbase-replication/README.md
> +with [reverse timestamps](https://hbase.apache.org/book.html#reverse.timestamp).
Suggest rephrasing this such as below to specify we're referring to the cell timestamps. Reverse timestamps are commonly used in the row key which may lead users to think they may be impacted by this, when they really aren't.

`Another special case is mutations with custom cell timestamps.`

2022-02-28 22:38 UTC, jhambleton commented on hbase-migration-tools/bigtable-hbase-replication/README.md
> +impacted use case is the reverse timestamp, where customers
slight edit based on the prior suggestion.

`The impacted use case is custom timestamps, where customers ... `

2022-03-01 19:16 UTC, jhambleton approved these changes
thanks for the updates, lgtm

2022-03-01 19:31 UTC, mutianf approved these changes

2022-03-01 22:08 UTC, merged