Client config pretty print
googleapis/java-bigtable-hbase pull request #3877
Opened 2022-12-03 20:41 UTC by kongweihan

2022-12-03 20:41 UTC, kongweihan commented
@igorbernstein2

2022-12-15 20:20 UTC, mutianf requested changes
Can you also fix the pr name to follow the convention? something like `chore: pretty print the settings`

2022-12-15 20:20 UTC, mutianf commented on bigtable-client-core-parent/bigtable-hbase/src/main/java/org/apache/hadoop/hbase/client/AbstractBigtableConnection.java
> +  public static class ToStringHelperPrettyPrinter {
I don't think this needs to be public

2022-12-15 20:20 UTC, mutianf commented on bigtable-client-core-parent/bigtable-hbase/src/main/java/org/apache/hadoop/hbase/client/AbstractBigtableConnection.java
> +    public static String print(String str) {
Same here, I don't think this needs to be public

2022-12-15 21:42 UTC, mutianf approved these changes

2022-12-15 21:45 UTC, merged